all:
  children:
    fortigates:
      children:
        fortigate_hubs:
          hosts:
            fg01-hub:
              ansible_host: 172.17.100.101
        fortigate_spokes:
          hosts:
            fg02-spoke:
              ansible_host: 172.17.100.103