---
- name: Read Nautobot facts for FortiGate Hubs
  hosts: fortigates
  gather_facts: false
  tasks:
    - name: Read Nautobot facts for {{ inventory_hostname }}
      ansible.builtin.include_role:
        name: nautobot_facts

- name: Configure IPSEC tunnels on FortiGate Spoke
  hosts: fortigate_spokes
  gather_facts: false

  module_defaults:
    group/fortinet.fortios.fortios:
      access_token: "{{ vault_fortios_token }}"
      vdom: "{{ vdom }}"

  tasks:
    - name: IPSEC Phase1 IPSEC01 tunnel
      fortinet.fortios.fortios_vpn_ipsec_phase1_interface:
        state: present
        vpn_ipsec_phase1_interface:
          name: "{{ item }}_1"
          type: "static"
          interface: "{{ int_wan1 }}"
          remote_gw: "{{ hostvars[item].ip_wan1.split('/')[0] }}"
          ike_version: "2"
          peertype: "any"
          localid: "{{ inventory_hostname }}_ipsec01"
          net_device: "disable"
          add_route: "disable"
          exchange_interface_ip: "enable"
          exchange_ip_addr4: "{{ ip_lo_ipsec01.split('/')[0] }}"
          proposal: "aes256-sha256"
          dpd: "on-idle"
          dpd_retrycount: "2"
          dpd_retryinterval: "10"
          dhgrp: "20"
          authmethod: "psk"
          psksecret: "{{ vault_ipsec_psk }}"
      loop: "{{ groups['fortigate_hubs'] }}"
      loop_control:
        label: "{{ item }}"

    - name: IPSEC Phase2 IPSEC01 tunnel
      fortinet.fortios.fortios_vpn_ipsec_phase2_interface:
        state: present
        vpn_ipsec_phase2_interface:
          name: "{{ item }}_1"
          phase1name: "{{ item }}_1"
          proposal: "aes256-sha256"
          dhgrp: "20"
      loop: "{{ groups['fortigate_hubs'] }}"
      loop_control:
        label: "{{ item }}"

    - name: IPSEC Phase1 IPSEC02 tunnel
      fortinet.fortios.fortios_vpn_ipsec_phase1_interface:
        state: present
        vpn_ipsec_phase1_interface:
          name: "{{ item }}_2"
          type: "static"
          interface: "{{ int_wan2 }}"
          remote_gw: "{{ hostvars[item].ip_wan2.split('/')[0] }}"
          ike_version: "2"
          peertype: "any"
          localid: "{{ inventory_hostname }}_ipsec02"
          net_device: "disable"
          add_route: "disable"
          exchange_interface_ip: "enable"
          exchange_ip_addr4: "{{ ip_lo_ipsec02.split('/')[0] }}"
          proposal: "aes256-sha256"
          dpd: "on-idle"
          dpd_retrycount: "2"
          dpd_retryinterval: "10"
          dhgrp: "20"
          authmethod: "psk"
          psksecret: "{{ vault_ipsec_psk }}"
      loop: "{{ groups['fortigate_hubs'] }}"
      loop_control:
        label: "{{ item }}"

    - name: IPSEC Phase2 IPSEC02 tunnel
      fortinet.fortios.fortios_vpn_ipsec_phase2_interface:
        state: present
        vpn_ipsec_phase2_interface:
          name: "{{ item }}_2"
          phase1name: "{{ item }}_2"
          proposal: "aes256-sha256"
          dhgrp: "20"
      loop: "{{ groups['fortigate_hubs'] }}"
      loop_control:
        label: "{{ item }}"

    - name: Display results
      debug:
        msg:  
        - "{{ inventory_hostname }} -> IPSEC tunnels to hubs {{ groups['fortigate_hubs'] }} configured"